### PR TITLE
Various fixes for gamepedia api calls

### PR DESCRIPTION
**Pull request by MePsyDuck**
* Added logger for initial db setup.
* Added retry logic in case gamepedia API rate limits (429).
* Updated responses regex.

### CODE REVIEW

**Comment by MePsyDuck** [comment]
Also, since audio migration is almost over at gamepedia, maybe we can push the new code to the vm.

**Review by Jonarzz — APPROVED** [review]

**Comment by Jonarzz** [comment]
Did you change anything in the Travis build? Or is this build fail expected and will be fixed?

**Comment by MePsyDuck** [comment]
All builds for PRs will fail as they don't get to access private environment variables.

**Comment by Jonarzz** [comment]
Right! Sorry, I've forgotten.

**Comment by Jonarzz** [comment]
Unfortunately failed after the merge as well: https://travis-ci.org/Jonarzz/DotaResponsesRedditBot/builds/633617524

**Comment by MePsyDuck** [comment]
Fixed in #36. [Build](https://travis-ci.org/Jonarzz/DotaResponsesRedditBot) is passing now, badge should take some time to update.

**Comment by Jonarzz** [comment]
Great, thanks.

**Comment by MePsyDuck** [comment]
So can I go ahead and deploy this in VM?

**Comment by Jonarzz** [comment]
I think so, yeah.

**Pull request merged**
